### ISSUE TITLE
Do not see new job steps after installing zip to libext

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/powershell-sandbox-directory#2]
I plugged in the zip to libext and am not seeing new steps related to:

powershell-sandbox-directory-create

powershell-sandbox-directory-delete

in the Node Steps or Workflow Steps tab.  Am I missing something with this?

Project config looks like:

#Sat Feb 03 13:30:47 CST 2018
#edit below
project.description=powershell-test
project.jobs.gui.groupExpandLevel=1
project.name=powershell-test
project.nodeCache.delay=30
project.nodeCache.enabled=true
project.plugin.FileCopier.win-ps-file-copy.authenticationType=Negotiate
project.plugin.FileCopier.win-ps-file-copy.passwordStoragePath=keys/oisadm
project.plugin.NodeExecutor.win-ps-node-exec.authenticationType=Negotiate
project.plugin.NodeExecutor.win-ps-node-exec.passwordStoragePath=keys/oisadm
resources.source.1.config.file=/app/rundeckpro_fepoc/projects/powershell-test/etc/resources.xml
resources.source.1.config.format=resourcexml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=true
resources.source.1.config.requireFileExists=false
resources.source.1.type=file
service.FileCopier.default.provider=win-ps-file-copy
service.NodeExecutor.default.provider=win-ps-node-exec

**Comment by miguelantonio** [comment]
Hi Fred,
Can you share your rundeck version and any error on the logs files related with the plugin?
Thanks

**Comment by miguelantonio** [comment]
Hi Fred,
It was a problem with the release, I generated a new one.
Let me know if this one works for you.
