### ISSUE TITLE
Clarification on parameters

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/powershell-sandbox-directory#3]
Can you please clarify what the parameters are for this plugin?

- destination (looks like destination directory to create)
- The identity string (?)
- The temp directory (?)

Our linux version only has "destination / basedir" parameter, and we default it with a string like:

${globals.jobtmp}/${job.project}/${job.name}/${job.execid}

How does that translate to what has been functionally delivered with this plugin?  Would like to make sure we can also make reference to project globals as well as job variables, as defined above.

**Comment by miguelantonio** [comment]
Hi @fellenberger I uploaded a clarification README for the parameters:
https://github.com/rundeck-plugins/powershell-sandbox-directory

I'll close the issue, for now, just reopen or create a new one if you need further assistance

**Comment by fellenberger** [comment]
Thx.  Reviewed the readme but I still don't see info on "The temp directory"

**Comment by fellenberger** [comment]
ok I see with the latest release "The temp directory" has been removed.
