### ISSUE TITLE
Directory not created

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/powershell-sandbox-directory#5]
Added a step to create sandbox dir c:\temp\12345, step did not fail, tried to 'ls c:\temp\12345' after that and step failed.

Node is defined as:

<project>
<node name="apset2771" description="Windows" tags="win" hostname="apset2771.ms.ds.uhc.com" osArch="amd64" osFamily="windows" osName="Windows Server" osVersion="6.3" username="MS\runx_oisadm"/>
</project>

![create_dir](https://user-images.githubusercontent.com/10405889/35840631-5e20ac66-0aac-11e8-87b5-21b50a4273cc.png)
![ls](https://user-images.githubusercontent.com/10405889/35840633-60ffe8d4-0aac-11e8-8d75-b2251620881a.png)

**Comment by fellenberger** [comment]
Looking at the .ps1 files included in the plugin bundle, I'm not seeing any code that would create or delete directories.  Please advise.

$ ls -ltr
total 8
-rw-r--r-- 1 rundeck rundeck 21 Feb  4 23:22 Sandbox-Delete.ps1
-rw-r--r-- 1 rundeck rundeck 21 Feb  4 23:22 Sandbox-Create.ps1
rundeck@apsrd7130:/tmp/powershell/powershell-sandbox-directory-steps-1.0.1/contents
$ more Sandbox-Delete.ps1
#Requires -Version 4
rundeck@apsrd7130:/tmp/powershell/powershell-sandbox-directory-steps-1.0.1/contents
$ more Sandbox-Create.ps1
#Requires -Version 4
rundeck@apsrd7130:/tmp/powershell/powershell-sandbox-directory-steps-1.0.1/contents
$

**Comment by miguelantonio** [comment]
Hi @fellenberger it seems you are using a previous version, sorry I didn't explain properly about it, here is an updated version of the plugin https://github.com/rundeck-plugins/powershell-sandbox-directory/releases/tag/1.0.2

just to make sure you are using this new version, you can just delete the previous plugin version and cache from libext and then install this

I'll close the Issue for now, if you still have a problem you can reopen it or open a new one

**Comment by fellenberger** [comment]
Verified that Create and Delete Sandbox job steps are working as expected now.  Thanks!

**Comment by miguelantonio** [comment]
Awesome, thanks!
